### ISSUE TITLE
AttributeError: 'module' object has no attribute 'parse'

### ISSUE THREAD

**Issue by xaionaro** [schollz/playlistfromsong#36]
```
$ playlistfromsong -s 'deep purle child of time'
Generating playlist for 3 songs from 'deep purle child of time'

PLAYLIST: 

Deep Purple - Child In Time (Son Of Aleric - Instrumental)
Traceback (most recent call last):
  File "/usr/local/bin/playlistfromsong", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playlistfromsong/cli.py", line 33, in main
    run(song, num, bearer=bearer, folder=folder)
  File "/usr/local/lib/python2.7/dist-packages/playlistfromsong/playlistfromsong.py", line 296, in run
    youtubeLinks = useLastFM(song, num)
  File "/usr/local/lib/python2.7/dist-packages/playlistfromsong/playlistfromsong.py", line 209, in useLastFM
    data = getYoutubeAndRelatedLastFMTracks(firstURL)
  File "/usr/local/lib/python2.7/dist-packages/playlistfromsong/playlistfromsong.py", line 169, in getYoutubeAndRelatedLastFMTracks
    '%s - %s official' % (artistName, songName))
  File "/usr/local/lib/python2.7/dist-packages/playlistfromsong/playlistfromsong.py", line 58, in getYoutubeURLFromSearch
    urlToGet = "https://www.youtube.com/results?search_query=" + urllib.parse.quote_plus(searchString)  # NOQA
AttributeError: 'module' object has no attribute 'parse'
```

**Comment by xaionaro** [comment]
$ python --version
Python 2.7.13

**Comment by syc728** [comment]
@xaionaro you can check the pr #34 (not merged by @schollz ) to fix the issue.

You can use the following code to support python 2.7 if you are familiar with Python
```python
if pyVersion < 3:
    urlParse = urllib.quote_plus(searchString)
else:
    urlParse = urllib.parse.quote_plus(searchString)
```

**Comment by schollz** [comment]
@xaionaro I've fixed the issue. Try it now by installing the update:

```
pip install --force --no-cache-dir  --upgrade playlistfromsong
```

**Comment by xaionaro** [comment]
Works, thanks :)

**Comment by aminaBm** [comment]
alias python=python3
