### ISSUE TITLE
Handle entering an artist without a song

### ISSUE THREAD

**Issue by xaionaro** [schollz/playlistfromsong#5]
Hello. I'm getting error "IndexError: list index out of range"
```
$ playlistfromsong -s 'Kalya Scintilla'

PLAYLIST: 

Desert Dwellers - Lotus Heart - (Kalya Scintilla Remix)
Kalya Scintilla - Kalya Scintilla
Kaya Project - Kaya Project
Androcell - Androcell
Kaminanda - Kaminanda
Ott - Ott
Shulman - Shulman
Bluetech - Bluetech
Shakatura - Shakatura
Hibernation - Hibernation
Desert Dwellers - Desert Dwellers
Master Minded - Master Minded
Kalya Scintilla -  similar
Kaya Project -  similar
Angel Tears - Angel Tears
Random Rab - Random Rab
Entheogenic - Entheogenic
Tripswitch - Tripswitch
Androcell -  similar
Kaminanda -  similar
Akasha - Akasha
Cell - Cell
Younger Brother - Younger Brother
Digital Mystery Tour - Digital Mystery Tour
Traceback (most recent call last):
  File "/usr/local/bin/playlistfromsong", line 9, in <module>
    load_entry_point('playlistfromsong==0.12', 'console_scripts', 'playlistfromsong')()
  File "/usr/local/lib/python2.7/dist-packages/playlistfromsong/__main__.py", line 213, in main
    youtubeLinks = useLastFM(song, num)
  File "/usr/local/lib/python2.7/dist-packages/playlistfromsong/__main__.py", line 140, in useLastFM
    for data in p.map(getYoutubeAndRelatedLastFMTracks, lastfmTracks):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
IndexError: list index out of range

$ python --version
Python 2.7.9
```

Best regards, Dmitry.

**Comment by schollz** [comment]
Yeah, I see its having a problem because you entered an artist and not an artist+song. The program is capturing similar artists when it thinks its capturing similar tracks. I will try to fix this in the future, but for the present try this:

```
$ playlistfromsong -s 'Kalya Scintilla Rises in the East'
```

**Comment by xaionaro** [comment]
Ok. I created the issue because I just expected a human readable error instead of a backtrace :)

It's not a problem as for me and thank you for this utility. I just reported a thing that I considered as an UX-problem :)

**Comment by syc728** [comment]
@schollz I see there is an argument _num_ to control the length of the generated playlist with default value 3, so I do not get the same error.
What i need to do is to add some readable descriptions, is it correct?

**Comment by schollz** [comment]
@syc728 Actually the problem is that sometimes a user might enter an artist and not a song. I think what needs to happen is that the closest match to the user input should be relayed back to the user.

For instance:

```
$ playlistfromsong -s 'Tom Petty'
Did you mean "Tom Petty - Refugee"? (y/n)
```

This can be the default behavior, actually, so that if someone does type a song it will still ask if that is the one that they meant:


```
$ playlistfromsong -s 'Led Zeppelin - Stairway to heaven'
Did you mean "Led Zeppelin - Stairway To Heaven"? (y/n)
```

If the user says "y" then it proceeds normally. If the user says "n" then it asks the user to retype the artist name + song name.

The functionality for finding the first seed song is already done, so it just needs to prompt the user to check to make sure it is correct.

**Comment by syc728** [comment]
@schollz Oh I got it! I will work on it.
